# Docker Compose format version:
#   The syntax follows v3
version: '3'

services: # list of container blueprints
  mariadb: # The database which stores and manges all your website's data like MySQL
    build: requirements/mariadb # directory of Dockerfile
    container_name: mariadb
    restart: always # when system reboots or craches unexpectedly
    env_file: .env # location of .env
    volumes: # Think of it as an external drive for containers
      - mariadb:/var/lib/mysql # name:directory
    networks: # name of internal network
      - inception

  wordpress: # Website builder
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on: # startup order
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  nginx: # Manges and delivers requests and responses
    build: requirements/nginx
    container_name: nginx
    restart: always
    env_file: .env
    ports: # entrance to the container from the outside
      - "443:443" # host's(computer's):container's
    depends_on: # startup order
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

volumes:
  mariadb:
    driver: local # where to store data => local storage
    driver_opts: 
      type: none # nfs, ext4...
      o: bind # bind: store data in your own directory below
      device: /home/${LOGIN:-hosu}/data/mariadb # directory
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN:-hosu}/data/wordpress

networks:
  inception:
    driver: bridge # communication method

# bridge: 컴퓨터 안에 가상의 네트워크 스위치(다리)를 하나 만들어
#         컨테이너끼리는 서로 대화할 수 있지만 외부에서는 함부로 들여다볼 수 없는 네트워크 방식
