version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hoskim/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hoskim/data/mariadb

networks:
  inception:
    driver: bridge
